apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: universal-auth-credentials
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: universal-auth-credentials
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        projectSlug: ml_plat-d3-fg
        environmentSlug: dev