apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Atharva-Phatak/dharma
    targetRevision: Atharva-Phatak/migrate_to_argo
    path: infrastructure/gitops/platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true  # Add this - retries if CRD missing
    retry:  # Add retry logic
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m