apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: arc-ns
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical  # Reference ClusterSecretStore
    kind: ClusterSecretStore        # Important: specify kind
  target:
    name: gha-rs-github-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: gh_token