apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster-store  # Reference ClusterSecretStore
    kind: ClusterSecretStore        # Important: specify kind
  target:
    name: gha-rs-github-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: gh_token
        property: token